spring:
  application:
    name: frontend
  data:
    redis:
      host: 192.168.1.108
      port: 6379

server:
  port: 8082

patient:
  service:
    base-url: http://gateway:8080/api/patients

note:
  service:
    base-url: http://gateway:8080/api/notes

risklevel:
  service:
    base-url: http://gateway:8080/api/risklevels

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8010/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: frontend

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com:
      medilabo:
        frontend: INFO
        frontend.controller: DEBUG
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG
