services:
  eureka:
    image: eureka
    ports:
      - "8010:8010"

  backend:
    image: backend
    ports:
      - "8081:8081"
    depends_on:
      - eureka

  note:
    image: note
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - backend

  risklevel:
    image: risklevel
    ports:
      - "8084:8084"
    depends_on:
      - eureka
      - backend

  frontend:
    image: frontend
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - backend
      - note
      - risklevel

  gateway:
    image: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - backend
      - note
      - risklevel
      - frontend
