services:
  eureka:
    image: eureka
    ports:
      - "8010:8010"
    networks:
      - medilabo-net

  backend:
    image: backend
    ports:
      - "8081:8081"
    depends_on:
      - eureka
    networks:
      - medilabo-net

  note:
    image: note
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - backend
    networks:
      - medilabo-net

  risklevel:
    image: risklevel
    ports:
      - "8084:8084"
    depends_on:
      - eureka
      - backend
    networks:
      - medilabo-net

  frontend:
    image: frontend
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - backend
      - note
      - risklevel
    networks:
      - medilabo-net

  gateway:
    image: gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - backend
      - note
      - risklevel
      - frontend
    networks:
      - medilabo-net

networks:
  medilabo-net:
    driver: bridge
