spring:
  application:
    name: note
  data:
    redis:
      host: 192.168.1.108
      port: 6379
    mongodb:
      uri: mongodb://192.168.1.108:27017/medicalnotesdb

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8010/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: note

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG