spring:
  application:
    name: gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8085/.well-known/jwks.json  # Point vers votre service de sécurité
  cloud:
    gateway:
          routes:
            - id: backend
              uri: lb://backend
              predicates:
                - Path=/api/patients/**
              filters:
                - RemoveRequestHeader=Cookie  # Nettoyage des cookies inutiles pour éviter les fuites
            - id: frontend
              uri: lb://frontend
              predicates:
                - Path=/patients/**
            - id: note
              uri: lb://note
              predicates:
                - Path=/api/notes/**
            - id: risklevel
              uri: lb://risklevel
              predicates:
                - Path=/api/risklevels/**
            - id: security
              uri: lb://security
              predicates:
                - Path=/login
              filters:
                - RemoveRequestHeader=Cookie

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com:
      medilabo:
        gateway: INFO
        gateway.config: DEBUG
    org:
      springframework:
        security: DEBUG
        cloud:
          gateway: DEBUG
          gateway.route: DEBUG
          client:
            loadbalancer: DEBUG
