spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: backend
          uri: lb://backend
          predicates:
            - Path=/api/patients/**
        - id: frontend
          uri: lb://frontend
          predicates:
            - Path=/login, /patients/**
        - id: note
          uri: lb://note
          predicates:
            - Path=/api/notes/**
        - id: risklevel
          uri: lb://risklevel
          predicates:
            - Path=/api/risklevels/**

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8010/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
