server:
  port: 8010

eureka:
  client:
    register-with-eureka: false  # Cela empêche le serveur Eureka de s'enregistrer lui-même
    fetch-registry: false  # Il ne cherche pas de registres, car il est le serveur
  instance:
    hostname: eureka
    leaseRenewalIntervalInSeconds: 10  # Intervalle de renouvellement
    leaseExpirationDurationInSeconds: 30  # Temps avant de marquer le service DOWN
  server:
    enable-self-preservation: false  # Désactiver pour les tests (peut être activé en prod)

management:
  endpoints:
    web:
      exposure:
        include: "*"
