spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/medilabo
    username: root
    password: Qnyyera6!
  jpa:
    hibernate:
      ddl-auto: update  # create-drop !! REPLACE BY update IN PRODUCTION !!
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  data:
    redis:
      host: 192.168.1.108
      port: 6379

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
          gateway.route: DEBUG
          org.hibernate.SQL: DEBUG